/**
 * Cymbio 3 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The GetSupplierResponse model module.
* @module model/GetSupplierResponse
* @version 3.0.0
*/
export default class GetSupplierResponse {
    /**
    * Constructs a new <code>GetSupplierResponse</code>.
    * @alias module:model/GetSupplierResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>GetSupplierResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GetSupplierResponse} obj Optional instance to populate.
    * @return {module:model/GetSupplierResponse} The populated <code>GetSupplierResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSupplierResponse();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('stripe_publishable_key')) {
                obj['stripe_publishable_key'] = ApiClient.convertToType(data['stripe_publishable_key'], 'String');
            }
            if (data.hasOwnProperty('stripe_secret_key')) {
                obj['stripe_secret_key'] = ApiClient.convertToType(data['stripe_secret_key'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
            if (data.hasOwnProperty('subdomain')) {
                obj['subdomain'] = ApiClient.convertToType(data['subdomain'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} stripe_publishable_key
    */
    stripe_publishable_key = undefined;
    /**
    * @member {String} stripe_secret_key
    */
    stripe_secret_key = undefined;
    /**
    * @member {String} createdAt
    */
    createdAt = undefined;
    /**
    * @member {String} updatedAt
    */
    updatedAt = undefined;
    /**
    * @member {String} subdomain
    */
    subdomain = undefined;








}


