/**
 * Cymbio 3 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import GetVariantResponse from './GetVariantResponse';





/**
* The GetVariantsResponse model module.
* @module model/GetVariantsResponse
* @version 3.0.0
*/
export default class GetVariantsResponse extends Array {
    /**
    * Constructs a new <code>GetVariantsResponse</code>.
    * @alias module:model/GetVariantsResponse
    * @class
    * @extends Array
    */

    constructor() {
        
        super();
        

        
        

        

        return this;
    }

    /**
    * Constructs a <code>GetVariantsResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GetVariantsResponse} obj Optional instance to populate.
    * @return {module:model/GetVariantsResponse} The populated <code>GetVariantsResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetVariantsResponse();

            ApiClient.constructFromObject(data, obj, 'GetVariantResponse');

            
            

        }
        return obj;
    }









}


