/**
 * Cymbio 3 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ImportProductsSchemaField from './ImportProductsSchemaField';





/**
* The ImportProductsRequest model module.
* @module model/ImportProductsRequest
* @version 3.0.0
*/
export default class ImportProductsRequest {
    /**
    * Constructs a new <code>ImportProductsRequest</code>.
    * @alias module:model/ImportProductsRequest
    * @class
    * @param url {String} 
    * @param fileType {module:model/ImportProductsRequest.FileTypeEnum} 
    * @param schema {Array.<module:model/ImportProductsSchemaField>} 
    */

    constructor(url, fileType, schema) {
        

        
        

        this['url'] = url;this['file_type'] = fileType;this['schema'] = schema;

        
    }

    /**
    * Constructs a <code>ImportProductsRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ImportProductsRequest} obj Optional instance to populate.
    * @return {module:model/ImportProductsRequest} The populated <code>ImportProductsRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ImportProductsRequest();

            
            
            

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('file_type')) {
                obj['file_type'] = ApiClient.convertToType(data['file_type'], 'String');
            }
            if (data.hasOwnProperty('schema')) {
                obj['schema'] = ApiClient.convertToType(data['schema'], [ImportProductsSchemaField]);
            }
        }
        return obj;
    }

    /**
    * @member {String} url
    */
    url = undefined;
    /**
    * @member {module:model/ImportProductsRequest.FileTypeEnum} file_type
    */
    file_type = undefined;
    /**
    * @member {Array.<module:model/ImportProductsSchemaField>} schema
    */
    schema = undefined;






    /**
    * Allowed values for the <code>file_type</code> property.
    * @enum {String}
    * @readonly
    */
    static FileTypeEnum = {
    
        /**
         * value: "csv"
         * @const
         */
        "csv": "csv"    
    };



}


