/**
 * Cymbio
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PostVariantProperty model module.
* @module model/PostVariantProperty
* @version 3.0.0
*/
export default class PostVariantProperty {
    /**
    * Constructs a new <code>PostVariantProperty</code>.
    * @alias module:model/PostVariantProperty
    * @class
    * @param type {String} 
    * @param value {String} 
    */

    constructor(type, value) {
        

        
        

        this['type'] = type;this['value'] = value;

        
    }

    /**
    * Constructs a <code>PostVariantProperty</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PostVariantProperty} obj Optional instance to populate.
    * @return {module:model/PostVariantProperty} The populated <code>PostVariantProperty</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostVariantProperty();

            
            
            

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} type
    */
    type = undefined;
    /**
    * @member {String} value
    */
    value = undefined;








}


