/**
 * Cymbio
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PostSupplierRequest model module.
* @module model/PostSupplierRequest
* @version 3.0.0
*/
export default class PostSupplierRequest {
    /**
    * Constructs a new <code>PostSupplierRequest</code>.
    * @alias module:model/PostSupplierRequest
    * @class
    * @param name {String} 
    * @param subdomain {String} 
    */

    constructor(name, subdomain) {
        

        
        

        this['name'] = name;this['subdomain'] = subdomain;

        
    }

    /**
    * Constructs a <code>PostSupplierRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PostSupplierRequest} obj Optional instance to populate.
    * @return {module:model/PostSupplierRequest} The populated <code>PostSupplierRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostSupplierRequest();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('subdomain')) {
                obj['subdomain'] = ApiClient.convertToType(data['subdomain'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} subdomain
    */
    subdomain = undefined;








}


