/**
 * Cymbio
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PostVariantOption model module.
* @module model/PostVariantOption
* @version 3.0.0
*/
export default class PostVariantOption {
    /**
    * Constructs a new <code>PostVariantOption</code>.
    * @alias module:model/PostVariantOption
    * @class
    * @param type {module:model/PostVariantOption.TypeEnum} 
    * @param value {String} 
    */

    constructor(type, value) {
        

        
        

        this['type'] = type;this['value'] = value;

        
    }

    /**
    * Constructs a <code>PostVariantOption</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PostVariantOption} obj Optional instance to populate.
    * @return {module:model/PostVariantOption} The populated <code>PostVariantOption</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostVariantOption();

            
            
            

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/PostVariantOption.TypeEnum} type
    */
    type = undefined;
    /**
    * @member {String} value
    */
    value = undefined;






    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
    
        /**
         * value: "color"
         * @const
         */
        "color": "color",
    
        /**
         * value: "size"
         * @const
         */
        "size": "size",
    
        /**
         * value: "width"
         * @const
         */
        "width": "width"    
    };



}


