/**
 * Cymbio
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SuccessResponse model module.
* @module model/SuccessResponse
* @version 3.0.0
*/
export default class SuccessResponse {
    /**
    * Constructs a new <code>SuccessResponse</code>.
    * @alias module:model/SuccessResponse
    * @class
    * @param success {Boolean} 
    */

    constructor(success) {
        

        
        

        this['success'] = success;

        
    }

    /**
    * Constructs a <code>SuccessResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SuccessResponse} obj Optional instance to populate.
    * @return {module:model/SuccessResponse} The populated <code>SuccessResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SuccessResponse();

            
            
            

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} success
    */
    success = undefined;
    /**
    * @member {String} message
    */
    message = undefined;








}


